# Docker has specific installation instructions for each operating system.
# Please refer to the official documentation at https://docker.com/get-started/

# Pull the Node.js Docker image:
FROM node:22-alpine

# Verify the Node.js version:
RUN node --version

# Verify npm version:
RUN npm --version
